name: skarbnik
description: School class's expenses manager

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  built_collection: ^4.0.0
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  redux_thunk: ^0.2.1
  timeago: ^2.0.9
  font_awesome_flutter: ^8.1.0
  transparent_image: ^0.1.0
  photo_view: ^0.0.10
  share: ^0.5.3
  package_info: ^0.3.2
  color: ^2.1.1
  font_awesome: ^4.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
  
flutter:
  uses-material-design: true